const userMock = {
  login: 'ASOCezar',
  id: 86000531,
  node_id: 'MDQ6VXNlcjg2MDAwNTMx',
  avatar_url: 'https://avatars.githubusercontent.com/u/86000531?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/ASOCezar',
  html_url: 'https://github.com/ASOCezar',
  followers_url: 'https://api.github.com/users/ASOCezar/followers',
  following_url: 'https://api.github.com/users/ASOCezar/following{/other_user}',
  gists_url: 'https://api.github.com/users/ASOCezar/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/ASOCezar/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/ASOCezar/subscriptions',
  organizations_url: 'https://api.github.com/users/ASOCezar/orgs',
  repos_url: 'https://api.github.com/users/ASOCezar/repos',
  events_url: 'https://api.github.com/users/ASOCezar/events{/privacy}',
  received_events_url: 'https://api.github.com/users/ASOCezar/received_events',
  type: 'User',
  site_admin: false,
  name: 'Cézar A S Oliveira',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: 'Pessoa Desenvolvedora, apaixonado pela tecnologia e pela programação.\r\n"Trabalhe com o que você ama e nunca mais precisará trabalhar na vida." -Confúcio',
  twitter_username: null,
  public_repos: 22,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: '2021-06-16T12:19:59Z',
  updated_at: '2021-10-17T11:58:38Z',
};

export default userMock;
