const userMock = {
  login: '',
  id: 0,
  node_id: '',
  avatar_url: '',
  gravatar_id: '',
  url: '',
  html_url: '',
  followers_url: '',
  following_url: '',
  gists_url: '',
  starred_url: '',
  subscriptions_url: '',
  organizations_url: '',
  repos_url: '',
  events_url: '',
  received_events_url: '',
  type: '',
  site_admin: false,
  name: '',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: '',
  twitter_username: null,
  public_repos: 22,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: '',
  updated_at: '',
};

export default userMock;
